# Generated by Django 5.2.10 on 2026-01-30 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_create_leads',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='can_delete_leads',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='can_export_leads',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='manage_tech_pipeline',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='view_tech_pipeline',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lead',
            name='stage',
            field=models.CharField(choices=[('LEAD_IN', 'Lead In'), ('DISCOVERY', 'Discovery'), ('PROPOSAL', 'Proposal'), ('NEGOTIATION', 'Negotiation'), ('CLOSED_WON', 'Closed Won'), ('PROJECT_PREPARATION', 'Project Preparation'), ('PROJECT_INITIATION', 'Project Initiation'), ('IN_PROGRESS', 'In Progress'), ('UAT', 'UAT'), ('DELIVERED', 'Delivered'), ('SUPPORT', 'Support'), ('CLOSED_LOST', 'Closed Lost')], default='LEAD_IN', max_length=30),
        ),
        migrations.CreateModel(
            name='TechPipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('PLANNING', 'Planning'), ('DESIGNING', 'Designing'), ('EXECUTING', 'Executing'), ('REVIEW', 'Review'), ('TESTING', 'Testing')], default='PLANNING', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tech_pipeline', to='crm.lead')),
            ],
        ),
    ]
