# Generated by Django 5.2.10 on 2026-02-03 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_user_can_create_leads_user_can_delete_leads_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='advance_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='lead',
            name='project_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
