# Generated by Django 6.0 on 2026-02-03 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_lead_advance_amount_lead_project_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='stage',
            field=models.CharField(choices=[('NEW_INQUIRY', 'New Inquiry'), ('QUALIFICATION', 'Qualification'), ('DISCOVERY', 'Discovery'), ('PROPOSAL', 'Proposal'), ('NEGOTIATION', 'Negotiation'), ('WON', 'Won'), ('PROJECT_EXECUTION', 'Project Execution'), ('DELIVERED', 'Delivered'), ('LOST', 'Lost'), ('ON_HOLD', 'On Hold')], default='NEW_INQUIRY', max_length=30),
        ),
    ]
