# Generated by Django 6.0 on 2026-02-03 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_alter_lead_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='lead_generator',
            field=models.ForeignKey(blank=True, help_text='Team member who brought in this lead', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_leads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='revenue_threshold',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Monthly revenue target for incentive calculation', max_digits=12),
        ),
        migrations.CreateModel(
            name='RevenueRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.lead')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenue_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'month', 'year'], name='crm_revenue_user_id_f73f8d_idx')],
            },
        ),
    ]
