# Generated by Django 5.2.11 on 2026-02-12 18:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='issued_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
