# Generated by Django 5.2.11 on 2026-02-12 18:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_alter_invoice_issued_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='issued_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
