# Generated by Django 5.2.11 on 2026-02-26 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_alter_invoice_issued_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='closing_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='stage',
            field=models.CharField(db_index=True, default='New', max_length=50),
        ),
        migrations.AlterField(
            model_name='lead',
            name='assigned_team',
            field=models.CharField(choices=[('SALES', 'Sales'), ('ADMIN', 'Admin'), ('TECH', 'Tech')], db_index=True, default='SALES', max_length=20),
        ),
        migrations.AlterField(
            model_name='lead',
            name='stage',
            field=models.CharField(choices=[('NEW_INQUIRY', 'New Inquiry'), ('QUALIFICATION', 'Qualification'), ('DISCOVERY', 'Discovery'), ('PROPOSAL', 'Proposal'), ('NEGOTIATION', 'Negotiation'), ('WON', 'Won'), ('PROJECT_EXECUTION', 'Project Execution'), ('DELIVERED', 'Delivered'), ('LOST', 'Lost'), ('ON_HOLD', 'On Hold')], db_index=True, default='NEW_INQUIRY', max_length=30),
        ),
    ]
