# Generated by Django 6.0.2 on 2026-02-27 08:33

from django.db import migrations


def migrate_invoices_to_quotations(apps, schema_editor):
    Invoice = apps.get_model('crm', 'Invoice')
    Quotation = apps.get_model('crm', 'Quotation')
    
    for invoice in Invoice.objects.all():
        Quotation.objects.create(
            quotation_number=invoice.invoice_number,
            client_name=invoice.client_name,
            client_email=invoice.client_email,
            client_address=invoice.client_address,
            payment_terms=invoice.payment_terms,
            items=invoice.items,
            grand_total=invoice.grand_total,
            issued_date=invoice.issued_date,
            status='SENT', # Default to SENT for old quotations
            created_by=invoice.created_by,
        )
    # Clear old invoices so they don't show up in the new Invoice list
    Invoice.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_quotation'),
    ]

    operations = [
        migrations.RunPython(migrate_invoices_to_quotations),
    ]
