# Generated by Django 5.2.11 on 2026-03-04 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_migrate_invoices_to_quotations'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='reminder_date',
            field=models.DateTimeField(blank=True, help_text='Automated or manual reminder date', null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
