# Generated by Django 5.2.11 on 2026-03-04 20:42

from django.db import migrations, models

def merge_names(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        cursor.execute('''
            UPDATE crm_lead 
            SET name = NULLIF(TRIM(COALESCE(first_name, '') || ' ' || COALESCE(last_name, '')), '')
            WHERE (first_name IS NOT NULL OR last_name IS NOT NULL);
        ''')

class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_lead_reminder_date_alter_lead_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='emirate',
            field=models.CharField(blank=True, choices=[('Abu Dhabi', 'Abu Dhabi'), ('Dubai', 'Dubai'), ('Sharjah', 'Sharjah'), ('Ajman', 'Ajman'), ('Umm Al Quwain', 'Umm Al Quwain'), ('Ras Al Khaimah', 'Ras Al Khaimah'), ('Fujairah', 'Fujairah')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='name',
            field=models.CharField(default='Unnamed Lead', max_length=255),
        ),
        migrations.RunPython(merge_names, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='lead',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='last_name',
        ),
    ]
