# Generated by Django 5.2.11 on 2026-03-04 22:05

from django.db import migrations


def migrate_names(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        cursor.execute('''
            UPDATE crm_lead 
            SET name = NULLIF(TRIM(COALESCE(first_name, '') || ' ' || COALESCE(last_name, '')), '')
            WHERE (name = '' OR name IS NULL OR name = 'Unnamed Lead');
        ''')

class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_lead_first_name_lead_last_name'),
    ]

    operations = [
        migrations.RunPython(migrate_names),
    ]
