# Generated by Django 5.2.11 on 2026-03-04 22:05

from django.db import migrations


def migrate_names(apps, schema_editor):
    Lead = apps.get_model('crm', 'Lead')
    for lead in Lead.objects.all():
        first = lead.first_name or ""
        last = lead.last_name or ""
        full_name = f"{first} {last}".strip()
        if full_name:
            lead.name = full_name
            lead.save()

class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_lead_first_name_lead_last_name'),
    ]

    operations = [
        migrations.RunPython(migrate_names),
    ]
