# Generated by Django 6.0.2 on 2026-03-07 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0018_defensive_data_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='industry',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
