# Generated by Django 5.2.11 on 2026-03-04 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0018_migrate_names'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='lead',
            name='emirate',
            field=models.CharField(blank=True, choices=[('DUBAI', 'Dubai'), ('ABU_DHABI', 'Abu Dhabi'), ('SHARJAH', 'Sharjah'), ('AJMAN', 'Ajman'), ('UMM_AL_QUWAIN', 'Umm Al Quwain'), ('RAS_AL_KHAIMAH', 'Ras Al Khaimah'), ('FUJAIRAH', 'Fujairah')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
