# Generated by Django 5.2.11 on 2026-03-05 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_remove_lead_first_name_remove_lead_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('INTERESTED', 'Interested'), ('NOT_INTERESTED', 'Not Interested'), ('NEEDS_FOLLOW_UP', 'Needs Follow-up')], db_index=True, default='INTERESTED', max_length=30),
        ),
    ]
