# Generated by Django 6.0.2 on 2026-03-10 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0019_lead_industry'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='latest_update',
            field=models.DateField(blank=True, help_text='Date of latest visit or update', null=True),
        ),
    ]
