# Generated by Django 6.0.2 on 2026-03-24 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0020_lead_latest_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='created_location_lat',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='created_location_link',
            field=models.CharField(blank=True, help_text='Google Maps link auto-captured at lead creation time', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='created_location_lng',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
    ]
