# Generated by Django 6.0.2 on 2026-03-05 21:52

from django.db import migrations, models


def merge_names(apps, schema_editor):
    Contact = apps.get_model('crm', 'Contact')
    User = apps.get_model('crm', 'User')

    for contact in Contact.objects.all():
        first = contact.first_name or ""
        last = contact.last_name or ""
        contact.name = f"{first} {last}".strip()
        contact.save()

    for user in User.objects.all():
        first = user.first_name or ""
        last = user.last_name or ""
        user.name = f"{first} {last}".strip()
        user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0020_lead_remarks_lead_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.RunPython(merge_names, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='contact',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
