# Generated by Django 6.0.2 on 2026-03-05 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0021_merge_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='reminder_date',
            field=models.DateField(blank=True, help_text='Automated or manual reminder date', null=True),
        ),
    ]
