# Generated by Django 6.0.2 on 2026-03-24 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0021_lead_creation_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='created_location_lat',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='created_location_lng',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True),
        ),
    ]
